### ISSUE TITLE
Carbon hangs at "preparing"

### ISSUE THREAD

**Issue by mschwerhoff** [viperproject/viper-ide#112]
# Problem

I had a long-running example open in VSCode. Now, when I start VSCode, verification starts with Silicon. Upon switching to Carbon, Silicon is aborted and Carbon starts `preparing`, but hangs their. I sometimes get the following output (in the `Output` panel at the bottom):

```
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.viper
starting server on  /tmp/app.viper 
starting TLS server false
starting server as Unix || Windows Socket
undefined:1
The server was not able to produce a timely response to your request.
^

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.<anonymous> (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\server\ViperServerService.js:389:37)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\request\request.js:1080:12)
    at IncomingMessage.emit (events.js:203:13)
    at IncomingMessage.Readable.read (_stream_readable.js:515:10)
    at flow (_stream_readable.js:984:34)
    at resume_ (_stream_readable.js:965:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Info  - 10:39:40] Connection to server got closed. Server will restart.
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.viper
starting server on  /tmp/app.viper 
starting TLS server false
starting server as Unix || Windows Socket
(node:18028) UnhandledPromiseRejectionWarning: Error: Unhandled method CheckIfSettingsVersionsSpecified
    at handleResponse (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\vscode-jsonrpc\lib\main.js:436:48)
    at processMessageQueue (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\vscode-jsonrpc\lib\main.js:263:17)
    at Immediate.<anonymous> (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\vscode-jsonrpc\lib\main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:18028) UnhandledPromiseRejectionWarning: Error: Unhandled method CheckIfSettingsVersionsSpecified
    at handleResponse (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\vscode-jsonrpc\lib\main.js:436:48)
    at processMessageQueue (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\vscode-jsonrpc\lib\main.js:263:17)
    at Immediate.<anonymous> (c:\Users\malte\.vscode-insiders\extensions\viper-admin.viper-2.2.2\node_modules\vscode-jsonrpc\lib\main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:18028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:18028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 10:42:45] Request textDocument/definition failed.
  Message: Request textDocument/definition failed unexpectedly without providing any details.
  Code: -32603 
[Error - 10:42:45] Request textDocument/definition failed.
  Message: Request textDocument/definition failed unexpectedly without providing any details.
  Code: -32603 
```

I've already re-installed/updated Viper from inside VSCode.

# Versions

**VSCode**
```
Version: 1.44.0-insider (system setup)
Commit: 0dbae2083aff6ff2190c8e2157be95458915d464
Date: 2020-04-03T05:44:09.945Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Viper**
```
v.2.2.2 — Viper Release 2020.1
```

**Java**
```
java 11.0.4 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
```

**Windows**
```
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.18363 N/A Build 18363
```

**Comment by ArquintL** [comment]
Since the latest pre-release, verification happens via ViperServer and switching backends is now basically a NOP. Thus, I'm going to close this issue for now. If the issue persists, please send me the file. Fixed by #113
